import type { TeamId } from "@/lib/world-cup-types";

export const teamFlagAssetMap: Record<TeamId, string> = {
  mex: "/flags/mexico.svg",
  rsa: "/flags/south-africa.svg",
  kor: "/flags/south-korea.svg",
  cze: "/flags/czech-republic.svg",
  can: "/flags/canada.svg",
  bih: "/flags/bosnia.svg",
  qat: "/flags/qatar.svg",
  sui: "/flags/switzerland.svg",
  bra: "/flags/brazil.svg",
  mar: "/flags/morocco.svg",
  hai: "/flags/haiti.svg",
  sco: "/flags/scotland.svg",
  usa: "/flags/usa.svg",
  par: "/flags/paraguay.svg",
  aus: "/flags/australia.svg",
  tur: "/flags/turkey.svg",
  ger: "/flags/germany.svg",
  cuw: "/flags/curacao.svg",
  civ: "/flags/ivory-coast.svg",
  ecu: "/flags/ecuador.svg",
  ned: "/flags/netherlands.svg",
  jpn: "/flags/japan.svg",
  swe: "/flags/sweden.svg",
  tun: "/flags/tunisia.svg",
  bel: "/flags/belgium.svg",
  egy: "/flags/egypt.svg",
  irn: "/flags/iran.svg",
  nzl: "/flags/new-zealand.svg",
  esp: "/flags/spain.svg",
  cpv: "/flags/cape-verde.svg",
  ksa: "/flags/saudi-arabia.svg",
  uru: "/flags/uruguay.svg",
  fra: "/flags/france.svg",
  sen: "/flags/senegal.svg",
  irq: "/flags/iraq.svg",
  nor: "/flags/norway.svg",
  arg: "/flags/argentina.svg",
  alg: "/flags/algeria.svg",
  aut: "/flags/austria.svg",
  jor: "/flags/jordan.svg",
  por: "/flags/portugal.svg",
  cod: "/flags/dr-congo.svg",
  uzb: "/flags/uzbekistan.svg",
  col: "/flags/colombia.svg",
  eng: "/flags/england.svg",
  cro: "/flags/croatia.svg",
  gha: "/flags/ghana.svg",
  pan: "/flags/panama.svg",
};

export function getTeamFlagAsset(teamId: TeamId) {
  return teamFlagAssetMap[teamId];
}
